apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: development
    project: tremplin-prime
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    environment: staging
    project: tremplin-prime
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: production
    project: tremplin-prime
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    environment: shared
    project: tremplin-prime
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-basic
  labels:
    environment: shared
    project: tremplin-prime